version: '3'
services:
  backend:
    build: ./backend
    volumes:
    - ./backend/:/usr/src/llm_service/
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
